export const CONTACT_FORM_VALIDATION = 'CONTACT_FORM_VALIDATION';
export const RESET_CONTACT_FORM = 'RESET_CONTACT_FORM';
export const CONTACT_FORM_VALUE_CHANGE_FN = 'CONTACT_FORM_CHANGE_FN';
export const CONTACT_FORM_VALUE_CHANGE_LN = 'CONTACT_FORM_CHANGE_LN';
export const CONTACT_FORM_VALUE_CHANGE_EM = 'CONTACT_FORM_CHANGE_EM';
export const CONTACT_FORM_VALUE_CHANGE_MG = 'CONTACT_FORM_CHANGE_MG';
